# org.freenas.autostart (default value: "false")
# org.freenas.capabilities-add (default value: "")
# org.freenas.capabilities-drop (default value: "")
# org.freenas.command (default value: "")
# org.freenas.privileged (default value: "false").
# org.freenas.expose-ports-at-host (default value: "false")
# org.freenas.interactive' (default value: "false")
# org.freenas.port-mappings (default value: none)
# org.freenas.settings (default value: [])
# org.freenas.static-volumes (default value: [])
# org.freenas.upgradeable (default value: "false")
# org.freenas.version (default value: '0')
# org.freenas.volumes (default value: [])
# org.freenas.web-ui-path (default: none)
# org.freenas.web-ui-port (default value: none)
# org.freenas.web-ui-protocol (default value: none)

FROM ubuntu:latest
LABEL org.freenas.interactive="true"
LABEL org.freenas.command="/bin/bash"
LABEL org.freenas.version="1"
LABEL org.freenas.upgradeable="false"
